// Next.js API route support: https://nextjs.org/docs/api-routes/introduction

export default (req, res) => {
  // Open Chrome DevTools to step through the debugger!
  // debugger;
  res.status(200).json({
    status: true,
    objects: [
      {"name": "Royal Alpaca Poncho Cape With Pockets", "id": 7120, "color": "Mixt. Natural-Beige-Grey.", "size": "O/S", "catalog": "SI", "fob": 114.1},
      {"name": "Wayfarer Alpaca Sweater", "id": 7451, "color": "Lt.Grey", "size": "M", "catalog": "NO", "fob": 52.70},
      {"name": "Agathe Turtleneck Alpaca Sweater", "id": 7870, "color": "Natural-Black", "size": "S", "catalog": "NO", "fob": 87.40},
      {"name": "Antonia Half-Zip Alpaca Sweater", "id": 7873, "color": "Black-Natural", "size": "M", "catalog": "NO", "fob": 61.20},
      {"name": "Princess Alpaca Cardigan", "id": 7885, "color": "Black-Natural", "size": "S", "catalog": "NO", "fob": 60.50},
      {"name": "Classic Alpaca Full-Zip Cardigan", "id": 7881, "color": "Black-Grey Mlge.", "size": "S", "catalog": "NO", "fob": 67.00},
      {"name": "Misha Alpaca Sweater Dress", "id": 6452, "color": "Black o Lt. Grey", "size": "O/S", "catalog": "NO", "fob": 68.50},
      {"name": "Annaisha Alpaca Sweater", "id": 6456, "color": "Black-Natural", "size": "M", "catalog": "NO", "fob": 43.50},
      {"name": "Ivane Alpaca Sweater", "id": 6093, "color": "Natural", "size": "M", "catalog": "NO", "fob": 62.90},
      {"name": "Beverly Alpaca Sweater", "id": 11666, "color": "Natural o Artic Blue", "size": "M", "catalog": "SI", "fob": 68.60},
      {"name": "Nordic Alpaca Cardigan With Claps", "id": 11976, "color": "Black-Natural", "size": "M", "catalog": "SI", "fob": 64.30},
      {"name": "Vera Baby Alpaca Cape", "id": 11672, "color": "Black-Natural", "size": "O/S", "catalog": "SI", "fob": 105.7},
      {"name": "Micaela Cable Alpaca Cardigan", "id": 9827, "color": "Beige", "size": "M", "catalog": "SI", "fob": 55.00},
      {"name": "Double-Face Alpaca Knit Ruana Wrap", "id": 6139, "color": "size, O/S", "catalog": "SI", "fob": 77.4},
      {"name": "Italy Alpaca Hat", "id": 306, "color": "Beige", "size": "O/S", "catalog": "SI", "fob": 15.20},
      {"name": "Italy Alpaca Fingerless Gloves", "id": 11185, "color": "Beige", "size": "O/S", "catalog": "SI", "fob": 12.9},
      {"name": "Herringbone Alpaca Hat", "id": 11931, "color": "Natural", "size": "O/S", "catalog": "SI", "fob": 14.70},
      {"name": "Herringbone Alpaca Fingerless Gloves", "id": 10985, "color": "Natural", "size": "O/S", "catalog": "SI", "fob": 13.9},
      {"name": "Scandinavian Winter Alpaca Hat - Fleece Lining", "id": 10803, "color": "Natural-Steel Blue-Green Mlge.", "size": "O/S", "catalog": "SI", "fob": 7.80},
      {"name": "Scandinavian Winter Alpaca Reversible Half Finger Gloves", "id": 10829, "color": "Natural-Steel Blue-Green Mlge.", "size": "O/S", "catalog": "SI", "fob": 13},
      {"name": "Norwegian Snowflakes Alpaca Hat", "id": 10821, "color": "Natural-Red-Blue Jade", "size": "O/S", "catalog": "SI", "fob": 10.30},
      {"name": "Norwegian Snowflakes Alpaca Glittens with broach", "id": 10805, "color": "Natural-Red-Blue Jade", "size": "O/S", "catalog": "SI", "fob": 14.1},
      {"name": "Snowfall Brushed Alpaca Hat", "id": 8943, "color": "Periwinkle", "size": "O/S", "catalog": "SI", "fob": 13.00},
      {"name": "Snowfall Brushed Alpaca Fingerless Gloves", "id": 10758, "color": "Periwinkle", "size": "O/S", "catalog": "SI", "fob": 9.9},
      {"name": "American Brushed Alpaca Hat", "id": 8956, "color": "Comb. Periwinkle-Natural", "size": "O/S", "catalog": "SI", "fob": 14.40},
      {"name": "American Brushed Alpaca Fingerless Gloves", "id": 9120, "color": "Comb. Periwinkle-Natural", "size": "O/S", "catalog": "SI", "fob": 10.3},
      {"name": "Aubrey Alpaca Knit Hat", "id": 9085, "color": "Ballet Rose Mlge.", "size": "O/S", "catalog": "SI", "fob": 13.30},
      {"name": "Aubrey Alpaca Knit Fingerless Gloves", "id": 9087, "color": "Ballet Rose Mlge.", "size": "O/S", "catalog": "SI", "fob": 10.4},
      {"name": "Nordic Brushed Alpaca Hat", "id": 9126, "color": "Black-Charcoal", "size": "O/S", "catalog": "SI", "fob": 8.80},
      {"name": "Nordic Brushed Alpaca Fingerless Gloves", "id": 9545, "color": "Black-Charcoal", "size": "O/S", "catalog": "SI", "fob": 10.8},
      {"name": "Colette Brushed Alpaca Hat", "id": 8519, "color": "Prussian Blue-Comb1", "size": "O/S", "catalog": "SI", "fob": 12.20},
      {"name": "Women's Double Knit English Alpaca Hat", "id": 6008, "color": "Coral Mlge.", "size": "O/S", "catalog": "SI", "fob": 14.50},
      {"name": "Alpaca Cable Fingerless Gloves", "id": 147, "color": "Gold", "size": "O/S", "catalog": "SI", "fob": 10.60},
      {"name": "Shadow Cable Alpaca Hat", "id": 3364, "color": "Beige", "size": "O/S", "catalog": "SI", "fob": 13.20},
      {"name": "Shadow Cable Alpaca Scarf", "id": 627, "color": "Beige", "size": "O/S", "catalog": "SI", "fob": 36.10},
      {"name": "Shadow Cable Alpaca Fingerless Gloves", "id": 6031, "color": "Beige", "size": "O/S", "catalog": "SI", "fob": 11.20},
      {"name": "Shadow Cable Alpaca Gloves", "id": 11916, "color": "Beige", "size": "O/S", "catalog": "SI", "fob": 16.00},
      {"name": "SNOWFALL HAT", "id": 999999, "color": "Sand Mlge.", "size": "O/S", "catalog": "NO", "fob": 19.7},
      {"name": "Reversible Alpaca Gloves Heavy Weight", "id": 3636, "color": "Charcoal-Lt. Grey", "size": "M", "catalog": "SI", "fob": 23.60},
      {"name": "Reversible Alpaca Mittens Heavy Weight", "id": 744, "color": "Charcoal-Lt. Grey", "size": "M", "catalog": "SI", "fob": 24.00},
      {"name": "Veruska Nordic Alpaca Headband", "id": 9157, "color": "Grey", "size": "O/S", "catalog": "SI", "fob": 9.6},
      {"name": "Veruska Nordic Alpaca Hat", "id": 9155, "color": "grey", "size": "O/S", "catalog": "NO", "fob": 10.20},
      {"name": "Veruska Nordic Alpaca Fingerless Gloves", "id": 9153, "color": "grey", "size": "O/S", "catalog": "SI", "fob": 9.3},
      {"name": "Unisex Reversible knit English Alpaca Hat", "id": 9345, "color": "Burgundy-Beige", "size": "O/S", "catalog": "SI", "fob": 16.20},
      {"name": "Ski Alpaca Mittens", "id": 6844, "color": "Black-Natural", "size": "O/S", "catalog": "SI", "fob": 13.20},
      {"name": "Ski Alpaca Headband", "id": 6910, "color": "Black-Natural", "size": "O/S", "catalog": "SI", "fob": 9.80},
      {"name": "Helena Alpaca Embroidered Hat - Fleece Lining", "id": 11216, "color": "Grey Mlge", "size": "O/S", "catalog": "SI", "fob": 13.40},
      {"name": "Helena Alpaca Embroidered Fingerless Gloves", "id": 11535, "color": "Grey Mlge", "size": "O/S", "catalog": "SI", "fob": 11.70},
      {"name": "Helena Alpaca Embroidered Mittens", "id": 11533, "color": "Grey Mlge", "size": "O/S", "catalog": "SI", "fob": 12.40},
      {"name": "Reversible Sand Dune Baby Alpaca Hat", "id": 8212, "color": "Comb. Black-Brown", "size": "O/S", "catalog": "NO", "fob": 15.80},
      {"name": "Alpaquita Unisex Socks", "id": 8962, "color": "BLACK GREY", "size": "S o M", "catalog": "SI", "fob": 9.90},
      {"name": "Fair Isle Alpaca Unisex Socks", "id": 11230, "color": "GREY HEATHER-BURGUNDY", "size": "L o XL", "catalog": "SI", "fob": 10.00},
      {"name": "Alpaca Print Unisex Crew Socks", "id": 11178, "color": "NATURAL GREY HEATHER", "size": "S o M", "catalog": "SI", "fob": 8.30},
      {"name": "Alpaca Ankle Alpaca Face Socks", "id": 11181, "color": "FRENCH PINK -BEIGE", "size": "L o XL", "catalog": "SI", "fob": 8.30},
      {"name": "Reindeer Holiday Crew Alpaca Socks", "id": 11598, "color": "DENIM NAVY", "size": "L o XL", "catalog": "SI", "fob": 9.80},
      {"name": "Alpaca Reindeer Unisex Socks", "id": 8679, "color": "RED- GREEN", "size": "L", "catalog": "SI", "fob": 8.80},
      {"name": "Dot Dress Crew Alpaca Socks", "id": 11313, "color": "BLACK", "size": "L o XL", "catalog": "SI", "fob": 6.80},
      {"name": "Unisex Shorty Geometric Alpaca Socks", "id": 11319, "color": "GRAPHITE BEIGE", "size": "S o M", "catalog": "SI", "fob": 5.30},
      {"name": "Alpaca Heavy Boot Unisex Socks", "id": 7925, "color": "BLACK", "size": "S, M y L", "catalog": "SI", "fob": 15.10},
      {"name": "Alpaca Boot Unisex Socks", "id": 7520, "color": "GREY", "size": "S o L", "catalog": "SI", "fob": 11.50},
      {"name": "Alpaca Outdoor Hiker Unisex Socks", "id": 7544, "color": "GREY HEATHER", "size": "S o L", "catalog": "SI", "fob": 10.90},
      {"name": "Alpaca Omni Hiker Unisex Socks", "id": 6099, "color": "MIX BLACK NATURAL ", "size": "L", "catalog": "SI", "fob": 10.80},
      {"name": "Colours Striped Alpaca Socks", "id": 8070, "color": "ARTIC BLUE", "size": "S o M", "catalog": "SI", "fob": 9.80},
      {"name": "Alpaca Therapeutic Unisex Socks", "id": 6141, "color": "GREY HEATHER", "size": "S o L", "catalog": "SI", "fob": 11.50},
      {"name": "Alpaca Ski & Snowboard Socks", "id": 9888, "color": "NAVY LT GREY BLACK", "size": "S o M", "catalog": "SI", "fob": 18.80},
      {"name": "Alpaca Ski & Snowboard Socks Light Weight", "id": 10548, "color": "BLACK GREY GREY HEATHER", "size": "L o XL", "catalog": "SI", "fob": 15.10},
      {"name": "Sport Golf Socks", "id": 6628, "color": "BALLT ROSE  MLAGE", "size": "S o M", "catalog": "SI", "fob": 6.20},
      {"name": "Men's Alpaca Crewneck Pullover Sweater", "id": 9830, "color": "NATURAL", "size": "M", "catalog": "SI", "fob": 50.50},
      {"name": "Men's Double Knit English Alpaca Hat", "id": 6286, "color": "Black", "size": "O/S", "catalog": "SI", "fob": 16.10},
      {"name": "Alpaca Mens Handmade Fingerless Gloves", "id": 644, "color": "Denim", "size": "O/S", "catalog": "SI", "fob": 11.10},
      {"name": "Men's Alpaca Half Finger Gloves", "id": 11078, "color": "Brown Heather", "size": "O/S", "catalog": "SI", "fob": 15.30},
      {"name": "Royal Baby Alpaca Scarf", "id": 570, "color": "Natural", "size": "O/S", "catalog": "NO", "fob": 33.50},
      {"name": "Woven & Brushed Baby Alpaca Scarf", "id": 584, "color": "Beige", "size": "O/S", "catalog": "NO", "fob": 26.80},
      {"name": "Stella Alpaca Reversible Coat", "id": 12026, "color": "Dk.Royal Blue-Grey Mlge.", "size": "S", "catalog": "SI", "fob": 184.60},
      {"name": "Reversible Alpaca Dress Coat", "id": 5763, "color": "Black-Grey Mlge.", "size": "S o M", "catalog": "SI", "fob": 180.60},
      {"name": "Sienna Baby Alpaca Cardigan", "id": 11664, "color": "Charcoal", "size": "S o M", "catalog": "SI", "fob": 59.00},
      {"name": "Baby Alpaca Camila Pullover", "id": 8933, "color": "Hazelnut or Natural", "size": "M", "catalog": "NO", "fob": 48.10},
      {"name": "Baby Alpaca Round Neck Pullover", "id": 8931, "color": "Ballet Rose Mlge.", "size": "M", "catalog": "NO", "fob": 44.40},
      {"name": "Nevada Alpaca Mittens - Fleece Lining", "id": 11763, "color": "Navy Comb.", "size": "O/S", "catalog": "SI", "fob": 14.40},
      {"name": "Nevada Alpaca Hat- Fleece Lining", "id": 11760, "color": "Navy Comb.", "size": "O/S", "catalog": "SI", "fob": 15.70},
      {"name": "Reversible Alessia Alpaca Hat", "id": 11821, "color": "Violet-Natural", "size": "O/S", "catalog": "SI", "fob": 21.10},
      {"name": "Garnet Baby Alpaca Hat", "id": 12066, "color": "Burgundy Melange", "size": "O/S", "catalog": "NO", "fob": 13.80},
      {"name": "Garnet Baby Alpaca Infinity Scarf", "id": 11198, "color": "Burgundy Melange", "size": "O/S", "catalog": "NO", "fob": 32.10},
      {"name": "Garnet Baby Alpaca Fingerless Gloves", "id": 11784, "color": "Burgundy Melange", "size": "O/S", "catalog": "SI", "fob": 14.60},
      {"name": "Scallop Lace Alpaca Hat", "id": 187, "color": "BABY BLUE", "size": "O/S", "catalog": "SI", "fob": 12.60},
      {"name": "Shadow Cable Alpaca Hat", "id": 3364, "color": "Violet", "size": "O/S", "catalog": "SI", "fob": 13.20},
      {"name": "Shadow Cable Alpaca Fingerless Gloves", "id": 6031, "color": "Violet", "size": "O/S", "catalog": "SI", "fob": 11.20},
      {"name": "Ilave Alpaca Hat with Ear Flaps", "id": 6904, "color": "NATURAL", "size": "O/S", "catalog": "SI", "fob": 17.70},
      {"name": "Ilave Alpaca Mittens", "id": 6906, "color": "NATURAL", "size": "O/S", "catalog": "SI", "fob": 12.90},
      {"name": "Shipibo Alpaca Boucle Gloves", "id": 6440, "color": "Magenta-Fucsia", "size": "O/S", "catalog": "SI", "fob": 11.00},
      {"name": "Shipibo Alpaca Boucle Hat with Ear Flaps", "id": 6267, "color": "Magenta-Fucsia", "size": "O/S", "catalog": "SI", "fob": 13.2},
      {"name": "Luxurious Comfort Alpaca Blanket", "id": 12033, "color": "Red - Brown - Camel", "size": "O/S", "catalog": "SI", "fob": 105.6},
      {"name": "Dallas Baby Alpaca Hat", "id": 7991, "color": "Mixt. Natural-Lavender", "size": "O/S", "catalog": "NO", "fob": 12.8},
      {"name": "Dallas Baby Alpaca Half Finger Gloves", "id": 7904, "color": "Mixt. Natural-Lavender", "size": "O/S", "catalog": "NO", "fob": 12.6},
      {"name": "Celtic Roots Alpaca Headband", "id": 11451, "color": "violet", "size": "O/S", "catalog": "SI", "fob": 9.9},
      {"name": "Scallop Lace Alpaca Fingerless Gloves", "id": 240, "color": "Baby Blue", "size": "O/S", "catalog": "SI", "fob": 11.0},
      {"name": "Olivia Alpaca Headband", "id": 11045, "color": "FRENCH PINK", "size": "O/S", "catalog": "SI", "fob": 10.7},
      {"name": "Colorful Brushed Alpaca Hat With Ear Flaps", "id": 11453, "color": "IVORY-APPLE CINNAMON", "size": "O/S", "catalog": "SI", "fob": 12.4},
    ]
  });
};
